export const LARGESIZEDSCREEN = 1280;
export const MEDIUMSIZEDSCREEN = 767;
export const STEPFORLARGESCREEN = 3;
export const STEPFORMEDIUMSCREEN = 2;
export const MOVIESTODISPLAYLARGESCREEN = 12;
export const MOVIESTODISPLAYMEDIUMSCREEN = 8;
export const MOVIESTODISPLAYSMALLSCREEN = 5;
